apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloudant
spec:
  hosts:
  - "*.cloudantnosqldb.appdomain.cloud"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cloudant
spec:
  hosts:
  - "*.cloudantnosqldb.appdomain.cloud"
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*.cloudantnosqldb.appdomain.cloud"
    route:
    - destination:
        host: "*.cloudantnosqldb.appdomain.cloud"
        port:
          number: 443
      weight: 100